crowdanki_uuid: 43c5ba66-9a65-11e8-90c9-a0481cc15658
name: Ultimate Geography
dyn: 0
extendNew: 10
extendRev: 50
deck_configurations:
- __type__: DeckConfig
  crowdanki_uuid: 43d37fac-9a65-11e8-9cc5-a0481cc15658
  name: Ultimate Geography
  autoplay: false
  dyn: false
  lapse:
    delays:
    - 10
    leechAction: 0
    leechFails: 8
    minInt: 1
    mult: 0
  maxTaken: 60
  new:
    bury: true
    delays:
    - 1
    - 10
    initialFactor: 2500
    ints:
    - 1
    - 4
    - 7
    order: 0
    perDay: 15
    separate: true
  replayq: true
  rev:
    bury: true
    ease4: 1.3
    fuzz: 0.05
    ivlFct: 1
    maxIvl: 36500
    minSpace: 1
    perDay: 100
  timer: 0
deck_config_uuid: 43d37fac-9a65-11e8-9cc5-a0481cc15658
